# Generated by Django 4.2 on 2025-01-08 23:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('imatge', models.ImageField(blank=True, null=True, upload_to='usuaris/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cataleg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=100)),
                ('autor', models.CharField(blank=True, max_length=200, null=True)),
                ('CDU', models.CharField(max_length=40)),
                ('signatura', models.CharField(max_length=40)),
                ('data_edicio', models.DateField(blank=True, null=True)),
                ('resum', models.TextField(blank=True, null=True)),
                ('anotacions', models.TextField(blank=True, null=True)),
                ('mides', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registre', models.CharField(blank=True, max_length=100, null=True)),
                ('exclos_prestec', models.BooleanField(default=True)),
                ('baixa', models.BooleanField(default=False)),
                ('cataleg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.cataleg')),
            ],
        ),
        migrations.CreateModel(
            name='Llengua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuari', models.CharField(blank=True, max_length=100, null=True)),
                ('accio', models.CharField(max_length=100)),
                ('data_accio', models.DateTimeField(auto_now_add=True)),
                ('tipus', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BR',
            fields=[
                ('cataleg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.cataleg')),
                ('productora', models.CharField(max_length=100)),
                ('duracio', models.TimeField()),
            ],
            bases=('biblioteca.cataleg',),
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('cataleg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.cataleg')),
                ('discografica', models.CharField(max_length=100)),
                ('estil', models.CharField(max_length=100)),
                ('duracio', models.TimeField()),
            ],
            bases=('biblioteca.cataleg',),
        ),
        migrations.CreateModel(
            name='Dispositiu',
            fields=[
                ('cataleg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.cataleg')),
                ('marca', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('biblioteca.cataleg',),
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('cataleg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.cataleg')),
                ('productora', models.CharField(max_length=100)),
                ('duracio', models.TimeField()),
            ],
            bases=('biblioteca.cataleg',),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.exemplar')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prestec', models.DateField(auto_now_add=True)),
                ('data_retorn', models.DateField(blank=True, null=True)),
                ('anotacions', models.TextField(blank=True, null=True)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.exemplar')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('descripcio', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge', models.ImageField(upload_to='imatges/')),
                ('cataleg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.cataleg')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='cataleg',
            name='tags',
            field=models.ManyToManyField(to='biblioteca.categoria'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.centre'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='cicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.cicle'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('cataleg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.cataleg')),
                ('ISSN', models.CharField(max_length=13)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('lloc', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('volums', models.IntegerField(blank=True, null=True)),
                ('pagines', models.IntegerField()),
                ('llengua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.llengua')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.pais')),
            ],
            bases=('biblioteca.cataleg',),
        ),
        migrations.CreateModel(
            name='Llibre',
            fields=[
                ('cataleg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.cataleg')),
                ('ISBN', models.CharField(max_length=13)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('colleccio', models.CharField(blank=True, max_length=100, null=True)),
                ('lloc', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('volums', models.IntegerField(blank=True, null=True)),
                ('pagines', models.IntegerField()),
                ('llengua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.llengua')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.pais')),
            ],
            bases=('biblioteca.cataleg',),
        ),
    ]
