# Generated by Django 4.2 on 2025-01-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_categoria_options_alter_llengua_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llibre',
            name='info_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='llibre',
            name='preview_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='llibre',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
