# Generated by Django 4.2 on 2025-01-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_llibre_info_url_llibre_preview_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataleg',
            name='titol_original',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cataleg',
            name='titol',
            field=models.CharField(max_length=200),
        ),
    ]
