# Generated by Django 4.2.18 on 2025-02-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_cataleg_titol_original_alter_cataleg_titol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='auth_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
